name: Run Tests 🧪

on: 
  push:
      branches:
          - main
          - develop
          #- 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  buildAndTestForSomePlatforms:
    name: Test Unity version ${{ matrix.unityVersion }} | Platform ${{ matrix.targetPlatform }} | Test mode ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode
        unityVersion:
          # Main LTS version : https://unity3d.com/unity/qa/lts-releases
          - 2019.4.38f1
          - 2020.3.33f1
          - 2021.3.1f1
        targetPlatform:
          # - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          # - StandaloneLinux64 # Build a Linux 64-bit standalone.
          # - iOS # Build an iOS player.
          # - Android # Build an Android player.
          # - WebGL # WebGL.
        projectPath:
          - ./package/${{ github.repository }}
          
    steps:
      # Checkout sandbox project
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
          
      # Caching dependencies and build outputs to improve workflow execution time
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
     
      - name: copy dir to new dir
        run: |
          pwd
          folderName=$(echo "${PWD##*/}")
          rsync -r "$GITHUB_WORKSPACE" "package" 
          ls -F "package/$folderName"
            
      ################################
      #     Check sample folder      #
      ################################      
      - name: Check sample folder
        run: |
          echo ""
          echo "##############################"
          echo "#    Check sample folder     #"
          echo "##############################"
          echo ""
          echo ""
          if exist Sample.meta then
             echo "Sample.meta exist and pollut your environement"
             exit 1
          fi

          if exist ./Sample/ then
             echo "Sample.meta exist and pollut your environement"
             exit 1
          fi
            
      # Run tests
      - name: "Run tests"
        uses: game-ci/unity-test-runner@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: ${{ matrix.unityVersion }}
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          packageMode: true
           # List of parameters here : https://docs.unity3d.com/Manual/CommandLineArguments.html
          customParameters: -nographics assemblyFilters:+[YourCompany].[YourPackageName].*,-*Tests*
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport'
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          
      # Upload coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Package Coverage results (edit + play, ${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-${{ matrix.testMode }}
          path: ${{ steps.testRunner.outputs.coveragePath }}
          retention-days: 1
